# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blueprint/AboutWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 241)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 398, 222))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.appIcon = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.appIcon.setText("")
        self.appIcon.setPixmap(QtGui.QPixmap("blueprint/../assets/imgs/ffmpeg_icon.png"))
        self.appIcon.setObjectName("appIcon")
        self.horizontalLayout.addWidget(self.appIcon)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.appVersion = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.appVersion.setFont(font)
        self.appVersion.setObjectName("appVersion")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.appVersion)
        self.ffmpegVersionLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ffmpegVersionLabel.setFont(font)
        self.ffmpegVersionLabel.setObjectName("ffmpegVersionLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ffmpegVersionLabel)
        self.ffmpegVersion = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ffmpegVersion.setFont(font)
        self.ffmpegVersion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ffmpegVersion.setObjectName("ffmpegVersion")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ffmpegVersion)
        self.appName = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.appName.setFont(font)
        self.appName.setObjectName("appName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.appName)
        self.appVersionLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Hiragino Kaku Gothic Pro")
        self.appVersionLabel.setFont(font)
        self.appVersionLabel.setObjectName("appVersionLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.appVersionLabel)
        self.authorLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Hiragino Kaku Gothic Pro")
        self.authorLabel.setFont(font)
        self.authorLabel.setObjectName("authorLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.authorLabel)
        self.author = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.author.setFont(font)
        self.author.setObjectName("author")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.author)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.closeButton.setFont(font)
        self.closeButton.setAutoDefault(False)
        self.closeButton.setDefault(True)
        self.closeButton.setFlat(False)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.appVersion.setText(_translate("Dialog", "N/A"))
        self.ffmpegVersionLabel.setText(_translate("Dialog", "FFmpeg: "))
        self.ffmpegVersion.setText(_translate("Dialog", "N/A"))
        self.appName.setText(_translate("Dialog", "FFmpeg GUI"))
        self.appVersionLabel.setText(_translate("Dialog", "バージョン: "))
        self.authorLabel.setText(_translate("Dialog", "作者"))
        self.author.setText(_translate("Dialog", "Unknown"))
        self.closeButton.setText(_translate("Dialog", "close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
